Add Sync Tabs button to Results View
mitre/heimdall2 pull request #1012
Opened 2021-03-02 17:15 UTC by camdenmoors

Closes #943, adds a "Sync Tabs" button to results view.

2021-03-02 22:31 UTC, rbclark approved these changes
Sonarcloud warnings, but other than those this looks good.

2021-03-05 16:09 UTC, rbclark commented
Blocked by discussion on https://github.com/mitre/heimdall2/pull/979

2021-03-08 15:51 UTC, camdenmoors commented
Disregard review request, didn't notice the blocker.

2021-03-09 23:56 UTC, rbclark requested changes
When sync is unchecked, it should default back to the 'Test' tab again.

2021-03-15 20:22 UTC, rbclark requested changes
Could this be reshaped to use computed getters and setters like the expand all feature does?

2021-03-15 20:22 UTC, rbclark commented on apps/frontend/src/components/cards/controltable/ControlTable.vue
> +  expandAll = false;
This shouldn't be necessary with the changes in master.

2021-03-15 20:22 UTC, rbclark commented on apps/frontend/src/components/cards/controltable/ControlTable.vue
> +    if(!this.syncTabs){
Since it's already a parameter here, may as well just use the passed in and not `this.syncTabs`.

2021-03-16 13:21 UTC, camdenmoors commented
> Could this be reshaped to use computed getters and setters like the expand all feature does?

I believe it should be fine as a boolean value as all it does is determine if the tab should be synced on update.
```
  async handleToggleSyncTabs(syncTabs: boolean): Promise<void> {
    if(!syncTabs){
      this.tab = 'test';
    }
  }
```

2021-03-17 18:05 UTC, rbclark approved these changes

2021-03-17 18:27 UTC, merged