Add dropdown to Heimdall logo
mitre/heimdall2 pull request #143
Opened 2020-09-09 17:59 UTC by camdenmoors

Closes #134, adds a dropdown to the Heimdall logo with help/about

2020-09-10 16:18 UTC, Bialogs requested changes
- [ ] When hovering over the two new links they highlight in red/orange color. Should be gray and consistent with the rest of the app

- [ ] There are additional space (height, etc.) styles added to the two list items in the drop down. @rbclark and I feel like the drop-down looks better without that additional spacing.

2020-09-10 17:14 UTC, aaronlippold commented
The build is failing and there are merge conflicts

2020-09-11 18:51 UTC, aaronlippold commented
Given this change we should swap the light/dark icon and the drop down so it is on the far right side I think

2020-09-14 20:57 UTC, rbclark approved these changes

2020-09-14 21:02 UTC, merged