Allow owners to change users group role
mitre/heimdall2 pull request #1494
Opened 2021-06-16 16:25 UTC by samuelsunvold

Closes [#1027](https://github.com/mitre/heimdall2/issues/1027). Allow owners to change users group role.

Signed-off-by: Sam Sunvold <sunvoldsj@vcu.edu>

2021-06-22 14:06 UTC, camdenmoors submitted a review, later dismissed

2021-07-07 18:02 UTC, rbclark requested changes
When adding a new user, by default the role is shown as blank even though it defaults to member after save

https://user-images.githubusercontent.com/2308869/124807488-ce243800-df2b-11eb-9ba9-8f6eb341e690.mov

It is currently possible to demote all members of a group to members, making the group unmanageable by anyone.

https://user-images.githubusercontent.com/2308869/124807585-ed22ca00-df2b-11eb-99bd-5fa419d1baf0.mov

2021-07-21 16:25 UTC, Bialogs requested changes
Missing backend tests for this new function.

2021-07-21 16:25 UTC, Bialogs commented on apps/backend/src/groups/groups.controller.ts
> +  async updateGroupUserRole(
The route and method should match

2021-07-21 16:25 UTC, Bialogs commented on libs/interfaces/user/slim-user.interface.ts
> +  groupRole?: string;
Why is a return-only interface having readonly removed?

2021-07-21 16:25 UTC, Bialogs commented on apps/backend/src/groups/groups.service.ts
> +    updateGroupUser: AddUserToGroupDto
Seems like there should be an `updateGroupUser` dto instead of repurposing addusertogroup

2021-07-21 16:25 UTC, Bialogs commented on apps/backend/src/groups/groups.service.ts
> +      .find((userToUpdate) => updateGroupUser.userId === userToUpdate.id)
We have a user id from the DTO and we have the group id. It is more efficient to query for the GroupUser directly using SQL and not iterate a potentially large list of users in a group.

2021-07-21 16:25 UTC, Bialogs commented on apps/backend/src/groups/groups.service.ts
> +        updatedAt: new Date()
Are you sure `updatedAt` is not set automatically?

2022-03-02 19:51 UTC, aaronlippold commented
@camdenmoors @Amndeep7 what is blocking us here? Can we rebase this and get it off the board?

2022-03-02 19:53 UTC, Amndeep7 commented
We still haven't done the code review - work keeps on coming up.

2023-02-24 20:22 UTC, Rlin232 commented
Note to self: Add functionality for assigning owners upon group creation.

2023-03-10 18:33 UTC, Rlin232 commented
https://user-images.githubusercontent.com/38306648/224396196-cb74b175-e3b8-4b43-80e0-8f0797f50836.mov

Currently, updating the same user's role twice requires a hard refresh for the second update to register. Note that if we try to update a different user's role (or the same user's role, but in another group) this does not require a refresh. This is likely a reactivity issue that we will look into.

2023-03-15 22:23 UTC, Amndeep7 commented
Resolves https://github.com/mitre/heimdall2/issues/4038

2023-03-31 19:22 UTC, Amndeep7 requested changes

2023-03-31 19:22 UTC, Amndeep7 commented on apps/frontend/src/components/global/groups/Users.vue
> +  onUpdateGroupUserRole(newValue: string) {
use a more accurate parameter name

2023-03-31 19:22 UTC, Amndeep7 commented on apps/frontend/src/components/global/groups/Users.vue
> +  numberOfOwners(): number {
can have a better implementation using functional programming

2023-03-31 19:36 UTC, Amndeep7 approved these changes

2023-04-03 19:08 UTC, Amndeep7 requested changes
see DMs - the notification for the group being successfully created is fine; however, then we have one about axios failing for some reason.

2023-04-24 17:38 UTC, merged