Use vuetify resize
mitre/heimdall2 pull request #1520
Opened 2021-06-22 15:51 UTC by samuelsunvold

Closes #77. Allow owners to change users group role.

Signed-off-by: Sam Sunvold <sunvoldsj@vcu.edu>

2021-06-22 16:12 UTC, camdenmoors commented on apps/frontend/src/components/cards/treemap/Treemap.vue
> -//               preserveAspectRatio="xMidYMid meet"
Can this line be removed? It doesn't seem to describe anything.

2021-06-23 13:54 UTC, rbclark requested changes

2021-06-23 13:54 UTC, rbclark commented on apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
> +      <v-checkbox color="primary" label="Viewed" />
The latest commit to this branch seems like it was committed to the wrong branch. The 'Viewed' checkbox should be in a separate PR.

2021-06-23 16:09 UTC, camdenmoors approved these changes

2021-06-24 09:13 UTC, rbclark approved these changes

2021-06-24 09:26 UTC, merged