Added the ability to mark controls as viewed
mitre/heimdall2 pull request #1528
Opened 2021-06-23 16:38 UTC by samuelsunvold

Closes #1495. Add a way to mark controls as viewed.

Signed-off-by: Sam Sunvold <sunvoldsj@vcu.edu>

2021-06-24 10:38 UTC, rbclark requested changes
This may look better with the Viewed column centered:
<img width="778" alt="Screen Shot 2021-06-24 at 6 31 04 AM" src="https://user-images.githubusercontent.com/2308869/123248744-457eb400-d4b6-11eb-9d3b-bf2e4d92cb1e.png">

The headings are no longer properly aligned after this change:
<img width="844" alt="Screen Shot 2021-06-24 at 6 12 57 AM" src="https://user-images.githubusercontent.com/2308869/123248900-6f37db00-d4b6-11eb-9730-59d5eb74270e.png">


This breaks the layout on any screen size that isn't large:
<img width="444" alt="Screen Shot 2021-06-24 at 6 34 08 AM" src="https://user-images.githubusercontent.com/2308869/123249033-92628a80-d4b6-11eb-9a78-e3deee57a9c7.png">
<img width="680" alt="Screen Shot 2021-06-24 at 6 33 53 AM" src="https://user-images.githubusercontent.com/2308869/123248951-7c54ca00-d4b6-11eb-8a66-5394747d4be0.png">
<img width="1096" alt="Screen Shot 2021-06-24 at 6 33 41 AM" src="https://user-images.githubusercontent.com/2308869/123248952-7ced6080-d4b6-11eb-819f-211b4aededcc.png">

2021-06-24 10:38 UTC, rbclark commented on apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
> +  }
```suggestion
  set wasViewed(value: boolean) {
    this.controlWasWaived = value;
  }
```

2021-06-24 10:38 UTC, rbclark commented on apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
> +    </template>
```suggestion
    <template #viewed>
      <v-layout justify-center>
        <v-checkbox
          v-model="wasViewed"
          color="primary"
          hide-details
          class="align-center justify-center"
          @click="$emit('control-viewed', control)"
        />
      </v-layout>
    </template>
```

2021-06-24 15:14 UTC, camdenmoors approved these changes

2021-06-24 15:25 UTC, rbclark commented
There's an invisible button on the right side of visibility that is throwing off the center alignment

<img width="641" alt="Screen Shot 2021-06-24 at 11 23 39 AM" src="https://user-images.githubusercontent.com/2308869/123289648-a3bf8d00-d4de-11eb-8f3f-4882827dab75.png">

2021-06-29 17:06 UTC, aaronlippold commented
![Screen Shot 2021-06-29 at 11 05 57](https://user-images.githubusercontent.com/1486440/123839153-07c0c780-d8ca-11eb-8627-ad3da236262e.png)

This seems like a good model to borrow from ... if you need a reference ... click Files Changed on your PR :P

2021-06-29 17:07 UTC, aaronlippold commented
I like the highlighted view checkbox and the running count of filtered elements

2021-06-29 17:12 UTC, rbclark commented
> I like the highlighted view checkbox and the running count of filtered elements

You may want to clarify what you're looking for here, could you look at the netlify preview and describe what you want changed from there?

2021-07-21 13:33 UTC, rbclark requested changes
This PR seems to have a lot of unrelated changes showing up in it, can you reconcile it to only the required changes?

2021-07-27 23:30 UTC, rbclark requested changes
https://user-images.githubusercontent.com/2308869/127240492-c9516ac0-0c8b-404b-86ba-715d41c7ac88.mov

This seems to break all other sorting

2021-07-28 02:19 UTC, rbclark approved these changes

2021-07-28 14:39 UTC, merged