Adds User Onboarding and Results View Tour
mitre/heimdall2 pull request #1552
Opened 2021-06-30 05:25 UTC by sesheikholeslam

Closes #46. Implements an onboarding tour for the user which guides them through the entry interface of Heimdall. Additionally, a tour has been added to the "Results View" page of Heimdall after the user's first time loading files. 

**IMPORTANT:** Tours are only displayed once and will not be shown to the user if they have either completed, skipped, or canceled the tour. This has been done by locally storing a key in the user's cache (hopefully making this feature easily applicable to both Heimdall-Lite and Heimdall Server).

Below is a demonstration of both the onboarding and "Results View" Tour:

https://user-images.githubusercontent.com/66632401/123906266-d7b50b00-d941-11eb-9633-f44691ced310.mov

2021-06-30 12:38 UTC, rbclark commented
![Screen Shot 2021-06-30 at 8 38 04 AM](https://user-images.githubusercontent.com/2308869/123961589-82e3b580-d97e-11eb-93c7-b21bbf3e9a09.png)

This breaks in lite mode since there is no database tab.

2021-07-02 18:07 UTC, aaronlippold commented
The deploy preview on Netlify is not coming up
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'


On Fri, Jul 2, 2021 at 10:02 AM sonarcloud[bot] ***@***.***>
wrote:

> SonarCloud Quality Gate failed.
>
> [image: Bug]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=BUG> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=BUG> 0
> Bugs
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=BUG>
> [image: Vulnerability]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=VULNERABILITY> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=VULNERABILITY> 0
> Vulnerabilities
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=VULNERABILITY>
> [image: Security Hotspot]
> <https://sonarcloud.io/project/security_hotspots?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=SECURITY_HOTSPOT> [image:
> A]
> <https://sonarcloud.io/project/security_hotspots?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=SECURITY_HOTSPOT> 0
> Security Hotspots
> <https://sonarcloud.io/project/security_hotspots?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=SECURITY_HOTSPOT>
> [image: Code Smell]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=CODE_SMELL> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=CODE_SMELL> 1
> Code Smell
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=1552&resolved=false&types=CODE_SMELL>
>
> [image: No Coverage information]
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=1552>
> No Coverage information
> [image: 17.7%]
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=1552&metric=new_duplicated_lines_density&view=list> 17.7%
> Duplication
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=1552&metric=new_duplicated_lines_density&view=list>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitre/heimdall2/pull/1552#issuecomment-873102577>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALK42A2XY7H2XOEW4QX5M3TVXPJRANCNFSM47RSFPNQ>
> .
>

2021-07-06 19:17 UTC, camdenmoors commented on apps/frontend/src/components/generic/Tour.vue
> +                text: 'Here you can access the S3 buckett',
```suggestion
                text: 'Here you can access the S3 bucket',
```

2021-07-12 22:53 UTC, rbclark commented
@aaronlippold the deploy preview should now be working properly.

2021-07-13 16:25 UTC, camdenmoors requested changes

2021-07-13 16:25 UTC, camdenmoors commented on apps/frontend/src/components/generic/Tour.vue
> +
```suggestion
import {ServerModule} from '../../store/server';
```

2021-07-13 16:25 UTC, camdenmoors commented on apps/frontend/src/components/generic/Tour.vue
> +                  return document.querySelector('#select-tab-database') ? true : false;
```suggestion
                  return ServerModule.serverMode;
```

2021-07-13 16:25 UTC, camdenmoors commented on apps/frontend/src/components/generic/Tour.vue
> +                buttons: defaultButtons
```suggestion
                buttons: defaultButtons,
                showOn() {
                  return ServerModule.serverMode;
                }
```

2021-11-01 17:52 UTC, camdenmoors commented
Superseded by #2137

2021-11-01 17:52 UTC, closed without merging