Clean up ApexPieChart.vue to not do additional type casting, simplify…
mitre/heimdall2 pull request #197
Opened 2020-09-22 13:43 UTC by Bialogs

… plot options. Fix issue with label inside the donut chart persisting by showing total.

2020-09-22 14:45 UTC, rbclark requested changes
The charts are currently failing to display on the deploy preview.

2020-09-22 19:45 UTC, Bialogs commented
Blocked on https://github.com/apexcharts/apexcharts.js/issues/1923

2020-09-25 16:59 UTC, rbclark commented
> Blocked on [apexcharts/apexcharts.js#1923](https://github.com/apexcharts/apexcharts.js/issues/1923)

More specifically, this is causing errors on the console whenever a user clicks on a donut slice due to the linked issue.

2020-10-14 16:13 UTC, rbclark commented on apps/frontend/src/components/generic/ApexPieChart.vue
> +  @Prop({required: true}) readonly series!: Number[];
Should be:

```typescript
  @Prop({required: true, type: Array}) readonly categories!: Category<string>[];
  @Prop({required: true, type: Array}) readonly series!: Number[];
```

2020-10-14 20:36 UTC, rbclark commented
@Bialogs I skipped this in #342 since it was cleaned up here. Since it seems ApexCharts is not going to address our issue, I'm fine with us having the error display on the console since the actual functionality is improved even though there is an error.

2020-10-15 21:52 UTC, merged