Xccdf openscap
mitre/heimdall2 pull request #2303
Opened 2021-12-15 23:23 UTC by Amndeep7

Resolves https://github.com/mitre/heimdall_tools/issues/120

2021-12-15 23:24 UTC, Amndeep7 commented
@ccoffin pr is here for https://github.com/mitre/heimdall_tools/issues/120

2021-12-15 23:26 UTC, Amndeep7 commented
1) Need to verify if it's ok to put that sample into our repo for testing purposes
2) Need to verify if it works for @ccoffin's usecase
3) Need to ask @ejaronne some questions about the mapper (see many of the todos, ex. "loaded" as a status)
4) Look into potentially fixing some of the remaining todos (see the rest of the todos, ex. "file"/"counter" as variable names)

2021-12-28 03:52 UTC, georgedias requested changes

2021-12-28 03:52 UTC, georgedias commented on apps/frontend/src/store/report_intake.ts
> +        guessOptions.data.match(/xmlns.*http.*\/xccdf/) ||
Add comments here explaining what is the regex looking for.

2021-12-28 03:52 UTC, georgedias commented on libs/hdf-converters/src/burpsuite-mapper.ts
> -}
You moved the parseXml? I see that it is imported.

Realized that it was repeated over in all other parsers.

2021-12-28 21:32 UTC, camdenmoors approved these changes

2021-12-28 21:33 UTC, merged