prismaConverterDev
mitre/heimdall2 pull request #2696
Opened 2022-03-03 22:15 UTC by georgedias

2022-03-17 00:35 UTC, Amndeep7 requested changes

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +        version: HeimdallToolsVersion,
this should be specifying the version of the profile/test/prisma/whatever, not heimdall tools.  it also should not be "package version".  if that information is not provided, leave it as the empty string.

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +                    result += `\n\n${obj.Description}`;
imo better to have the description in the control's desc tag

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +              cve: {path: 'CVE ID'},
would probably add a cve published date tag and put the Published column in there

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +              cvss: {path: 'cssv'}
the header is wrong - it should be all caps i think

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +                status: ExecJSON.ControlResultStatus.Failed,
will there only ever be fails?

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/compliance/compliance_explorer.html

makes it seem like there might be passes as well

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +            descriptions: [],
might need to do conditional processing of the 'Description' in order to extract stuff like 'Mitigation' (analogous to fix text) and put it in here.  i think @ejaronne would be pretty interested in going through the possible variations that can exist within this field

2022-03-17 00:35 UTC, Amndeep7 commented on libs/hdf-converters/src/prisma-mapper.ts
> +            tags: {
i think you're missing a bunch of headers that you can probably shove in here or just leave in the code block i guess.  these include things like service/cluster/source package/etc.

2022-03-17 00:37 UTC, Amndeep7 commented
this is just stuff that i saw going through it relatively quickly.  i think @ejaronne should probably also go over this to figure out how best to map things.  that Description header in particular i think is gonna be a lot more work.

2022-03-22 17:02 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +  critial: 1
```suggestion
  critical: 1
```

2022-03-22 17:03 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +const BASE_NIST_TAG = ['SI-2', 'RA-5'];
Please differentiate between these two (either in a comment or by variable name)

2022-03-22 17:14 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +}
```suggestion
function nistTag(cveTag: Record<string, string>): string[] {
  if (!cveTag) {
    return DEFAULT_NIST_TAG;
  } else {
    return BASE_NIST_TAG;
  }
}
function getId(value: Record<string, string>): string {
  const complianceID = _.get(value, 'Compliance ID');
  const cveID = _.get(value, 'CVE ID');
  const distro = _.get(value, 'Distro');
  const severity = _.get(value, 'Severity');
  if (cveID) {
    return `${complianceID}-${cveID}`;
  } else {
    return `${complianceID}-${distro}-${severity}`;
  }
}
```

2022-03-22 20:52 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +const REMEDIATION_NIST_TAG = ['SI-2', 'RA-5'];
```suggestion
// The REMEDIATION_NIST_TAG the set of default applicable NIST 800-53 controls for ensuring up-to-date packages.
// SI-2 (FLAW REMEDIATION) - 	RA-5 (VULNERABILITY SCANNING)
const REMEDIATION_NIST_TAG = ['SI-2', 'RA-5'];
```

2022-03-22 20:53 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +const DEFAULT_NIST_TAG = ['SA-11', 'RA-5'];
```suggestion
// The DEFAULT_NIST_TAG is applicable to all automated configuration tests.
// SA-11 (DEVELOPER SECURITY TESTING AND EVALUATION) - RA-5 (VULNERABILITY SCANNING)
const DEFAULT_NIST_TAG = ['SA-11', 'RA-5'];
```

2022-03-22 20:55 UTC, camdenmoors commented on libs/hdf-converters/src/prisma-mapper.ts
> +  return hostName.toString().concat(distro, type);
```suggestion
  return `${hostName}-${distro}-${type}`;
```

2022-03-23 17:10 UTC, camdenmoors approved these changes

2022-03-23 19:27 UTC, merged