Ensure valid types for Nessus Mapper segments[].message
mitre/heimdall2 pull request #2900
Opened 2022-04-11 20:34 UTC by camdenmoors

2022-04-11 20:45 UTC, camdenmoors commented
Looks like we don't have any tests for this. I'm keeping this open until tests are finished. Non-sensitive sample data:
[Home_Network_4v072v.txt](https://github.com/mitre/heimdall2/files/8467605/Home_Network_4v072v.txt)

2022-04-13 15:30 UTC, Amndeep7 requested changes

2022-04-13 15:31 UTC, Amndeep7 commented on libs/hdf-converters/src/nessus-mapper.ts
> +                  path: ['plugin_output', 'cm:compliance-actual-value'],
Also please add tests like you mentioned in the comment above.

2022-04-14 17:12 UTC, Amndeep7 approved these changes

2022-04-14 17:13 UTC, merged