Create Collapsible Search-bar on Mobile
mitre/heimdall2 pull request #313
Opened 2020-10-09 18:23 UTC by camdenmoors

Closes #254, turns the search bar into a button when on displays with a width smaller than 600px.

2020-10-12 22:02 UTC, Bialogs requested changes
- When collapsing to mobile view, the clear filter button goes away.

- When clicking on search on < 600px screens, you cannot exit the search dialog unless you click into it first and then click somewhere else. Expected behavior would be that the search will always collapse back into a button when clicking anywhere else (this would also apply the search filter if anything was typed).

2020-10-16 18:57 UTC, Bialogs commented
As we discussed:

- Provide method for clearing the search text filter without clearing all filters

- Display clear all filters button when search bar is not expanded.

2020-10-20 21:42 UTC, Bialogs approved these changes

2020-10-20 22:02 UTC, aaronlippold commented
On my mobile device the tree map does not seem to be loading in this PR and
also the hamburger menu when switching between the comparison view and the
results view seems to be acting a little funky on the mobile device. Lastly
the profile info model seems to be over scanning the display area and it's
going outside the bounds of the application.

On Tue, Oct 20, 2020, 5:56 PM sonarcloud[bot] <notifications@github.com>
wrote:

> Kudos, SonarCloud Quality Gate passed!
>
> [image: Bug]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=BUG> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=BUG> 0
> Bugs
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=BUG>
> [image: Vulnerability]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=VULNERABILITY> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=VULNERABILITY> 0
> Vulnerabilities
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=VULNERABILITY>
> (and [image: Security Hotspot]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=SECURITY_HOTSPOT> 0
> Security Hotspots
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=SECURITY_HOTSPOT>
> to review)
> [image: Code Smell]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=CODE_SMELL> [image:
> A]
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=CODE_SMELL> 0
> Code Smells
> <https://sonarcloud.io/project/issues?id=mitre_heimdall2&pullRequest=313&resolved=false&types=CODE_SMELL>
>
> [image: No Coverage information]
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=313>
> No Coverage information
> [image: 0.0%]
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=313&metric=new_duplicated_lines_density&view=list> 0.0%
> Duplication
> <https://sonarcloud.io/component_measures?id=mitre_heimdall2&pullRequest=313&metric=new_duplicated_lines_density&view=list>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitre/heimdall2/pull/313#issuecomment-713163184>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALK42EWWBKY3RS6TSGDLODSLYBSLANCNFSM4SKMR5JQ>
> .
>

2020-10-20 22:15 UTC, merged