[WIP] Add Default CCIs for Relevant NIST Controls
mitre/heimdall2 pull request #3170
Opened 2022-06-15 18:37 UTC by camdenmoors

2022-06-23 20:38 UTC, em-c-rod reviewed
From a high level, it looks like these changes are generally to support a new tag field for CCIs. Is that option new? Or just wasn't in the testing before? Anything else to pay close attention to?

2022-06-24 10:42 UTC, camdenmoors commented
> From a high level, it looks like these changes are generally to support a new tag field for CCIs. Is that option new? Or just wasn't in the testing before? 
This is a new feature to support conversion to POA&M

> Anything else to pay close attention to?
That the data should be included on import and matches that of the included lookup table

2022-06-24 17:11 UTC, Amndeep7 requested changes

2022-06-24 17:11 UTC, Amndeep7 commented on libs/hdf-converters/src/twistlock-mapper.ts
> +              cci: getCCIsForNISTTags(['SI-2', 'RA-5']),
Don't we have a constant somewhere that defines our default nist tags?  Use that.

2022-06-24 17:11 UTC, Amndeep7 commented on libs/hdf-converters/src/utils/global.ts
> +      if (baseTag[0] in NistCciMappingData) {
combine the two conditionals with && in order to get rid of pointless nesting

2022-07-01 06:12 UTC, Amndeep7 commented
@camdenmoors bump

2022-07-08 14:55 UTC, Amndeep7 commented
@camdenmoors can you fix the merge conflict?  Also the veracode mapper was merged, so can you add the cci stuff there as well?

2022-07-12 15:48 UTC, merged