Updating Zap mapper formatting
mitre/heimdall2 pull request #3203
Opened 2022-06-21 17:56 UTC by charleshu-8

Signed-off-by: charleshu-mitre <chu@mitre.org>

2022-06-30 18:19 UTC, Rlin232 approved these changes

2022-06-30 18:26 UTC, Rlin232 commented on libs/hdf-converters/src/zap-mapper.ts
> +      transformer: (data: Record<string, any>): Record<string, unknown> => {
Avoid uses of "any" (I think this has been commented on other PR's already though)

2022-07-01 03:42 UTC, Amndeep7 requested changes

2022-07-01 03:42 UTC, Amndeep7 commented on libs/hdf-converters/src/zap-mapper.ts
> +              data: {
I think you could probably do ```data: _.pick(data, ['site.@port', 'site.@ssl'])```

See:

```js
const a = {a: {b: 5, c: 2, d: 3}, e: 1};
console.log(_.pick(a, ['a.b', 'a.c']));
```

which generates

```js
{
  a: {
    b: 5,
    c: 2
  }
}
```

2022-07-06 13:43 UTC, camdenmoors commented on libs/hdf-converters/src/zap-mapper.ts
>                check: {transformer: checkText}
Check and Fix are normally a description instead of a tag now

2022-07-06 13:44 UTC, camdenmoors commented on libs/hdf-converters/src/zap-mapper.ts
> +              }
```suggestion
              transformer: (vulnerability: Record<string, unknown>): string => JSON.stringify(vulnerability, null, 2);
```

2022-07-06 16:09 UTC, Amndeep7 commented
How does that check text look in heimdall?  It seems like it's HTML encoded.  If that's the case, maybe we can parse that too so that it looks pretty but maybe it already looks nice there?  Deploypreview is currently borked cause of the netlify injection I think so need to either push a fake commit or deploy from heroku.

2022-07-06 18:05 UTC, charleshu-8 commented
> How does that check text look in heimdall? It seems like it's HTML encoded. If that's the case, maybe we can parse that too so that it looks pretty but maybe it already looks nice there? Deploypreview is currently borked cause of the netlify injection I think so need to either push a fake commit or deploy from heroku.

Text itself comes out okay. Only problem I see are the new lines.

![Screenshot (13)](https://user-images.githubusercontent.com/106095667/177614660-b43c6390-71a1-4438-b1fa-99baba7707c1.png)
![Screenshot (14)](https://user-images.githubusercontent.com/106095667/177614663-f5fc20f2-c538-4ee8-a0e2-81abeb4af84b.png)
![Screenshot (15)](https://user-images.githubusercontent.com/106095667/177614666-87f8fdae-d430-45a8-b67c-0e21d6fcbc05.png)

2022-07-08 14:50 UTC, Amndeep7 approved these changes

2022-07-08 15:06 UTC, merged