Update mapper formatting for DBProtect, Fortify, Netsparker, XCCDF
mitre/heimdall2 pull request #3273
Opened 2022-07-05 16:49 UTC by charleshu-8

Signed-off-by: charleshu-mitre <chu@mitre.org>

2022-07-14 21:11 UTC, Rlin232 approved these changes

2022-07-14 21:11 UTC, Rlin232 commented on libs/hdf-converters/src/netsparker-mapper.ts
> +        const targetData = _.omit(_.get(auxData, 'target'), [
Could potentially just consolidate this to `_.get(data, 'netsparker-enterprise.generated')` and `_.get(data, 'netsparker-enterprise.target'`, but I feel like that might just be personal preference.

2022-07-18 04:16 UTC, Amndeep7 requested changes
I feel very uncomfortable making changes to the mapper when we don't have the ability to test and verify what the resulting output will look like.  We can talk on Monday for what this will look like, but I think we should a) see if we know who's using it who can lend us a sample, b) scour the internet to see if there's a sample uploaded online somewhere, and/or c) reach out to the company and request the schema for their output (happy path), limited time demo of their tool so we can run it against our own systems for a day or two (medium path), a sample output (worst case still good path).

2022-07-18 14:17 UTC, charleshu-8 commented
> I feel very uncomfortable making changes to the mapper when we don't have the ability to test and verify what the resulting output will look like. We can talk on Monday for what this will look like, but I think we should a) see if we know who's using it who can lend us a sample, b) scour the internet to see if there's a sample uploaded online somewhere, and/or c) reach out to the company and request the schema for their output (happy path), limited time demo of their tool so we can run it against our own systems for a day or two (medium path), a sample output (worst case still good path).

I have a working sample on-hand for both DbProtect and Netsparker that I received from @ejaronne and have been testing my changes against those. If you want me to send them to you for review purposes, just let me know.

2022-08-05 19:10 UTC, charleshu-8 commented
HANDOFF: Blocked by Heimdall2 PR #3273 (https://github.com/mitre/heimdall2/pull/3273); otherwise, should be good

2022-08-05 19:12 UTC, charleshu-8 commented
HANDOFF: Waiting on confirmation on usage of DBP & NS data for regression testing; otherwise, is ready for merging

2023-06-14 18:04 UTC, charleshu-8 commented
Separating out the mapper updates so I can deal with them individually as the sample files come in

2023-06-14 18:05 UTC, charleshu-8 commented
Separating out the mapper updates so I can deal with them individually as the sample files come in

2023-06-14 18:05 UTC, closed without merging