Updating XCCDF mapper formatting
mitre/heimdall2 pull request #3274
Opened 2022-07-05 17:59 UTC by charleshu-8

Signed-off-by: charleshu-mitre <chu@mitre.org>

2022-07-14 21:22 UTC, Rlin232 commented
> 

Not sure what to do about the SonarCloud complaining about the commented-out code. It is indeed useful to have in there for the sake of testing, so I'm of the opinion that we leave it in and ignore the SonarCloud stuff.

2022-07-18 04:17 UTC, Amndeep7 commented
> I'm of the opinion that we leave it in and ignore the SonarCloud stuff.

that's exactly what we're gonna do @Rlin232

2022-07-18 04:21 UTC, Amndeep7 requested changes
I would appreciate a chance to pair to see what the new output looks like just to confirm that it's all good.  Github don't wanna show diffs this large lol.

2022-07-18 04:21 UTC, Amndeep7 commented on libs/hdf-converters/src/xccdf-results-mapper.ts
>          name: {path: ['cdf:Benchmark.id', 'Benchmark.id']},
@camdenmoors mentioned something about how `cdf:` is some sorta prefix that we can tell the parser to ignore.  talk to him to see what's up with that so we can ideally simplify this mapper.

2022-07-19 19:33 UTC, Amndeep7 approved these changes

2022-07-19 19:34 UTC, merged