Updating mapper tests for withraw flag
mitre/heimdall2 pull request #3329
Opened 2022-07-13 19:54 UTC by charleshu-8

Signed-off-by: charleshu-8 <chu@mitre.org>

2022-07-14 21:05 UTC, Rlin232 approved these changes
Tests all look good to me.

2022-07-14 21:05 UTC, Rlin232 commented on libs/hdf-converters/test/mappers/forward/burpsuite_mapper.spec.ts
> +    //   'sample_jsons/burpsuite_mapper/burpsuite-hdf-withraw.json',
Should we remove this commented out bit?

2022-07-14 21:05 UTC, Rlin232 commented on libs/hdf-converters/test/mappers/forward/burpsuite_mapper.spec.ts
> +    //   'sample_jsons/burpsuite_mapper/burpsuite-hdf-withraw.json',
Nevermind - I see the purpose!

2022-07-18 04:04 UTC, Amndeep7 requested changes

2022-07-19 19:06 UTC, Amndeep7 approved these changes

2022-07-19 19:23 UTC, merged