Workflow updates
mitre/heimdall2 pull request #3927
Opened 2023-01-04 22:23 UTC by wdower

- Bumps up versions for github action workflows
- Bumps the version of node used by the workflows to 16
- fixes a busted test for the backend

2023-01-04 23:10 UTC, Amndeep7 requested changes

2023-01-05 14:47 UTC, em-c-rod commented on .github/workflows/backend-tests.yml
> +       uses: actions/setup-node@v3
I did remove the actions/cache action when updating workflows in `ts-inspec-objects`

2023-01-05 15:00 UTC, em-c-rod requested changes
Thanks for updating these workflows. I think we can remove the actions/cache actions and use the actions/setup-node to cache dependencies.

Ex:
```
- uses: actions/setup-node@v3
  with:
    node-version: 16
    cache: 'yarn'
    cache-dependency-path: subdir/package-lock.json 
 ```
 
More information about the cache-dependency-path can be found here: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
I am not sure if we can utilize the cache-dependency-path without storing the library lock files.

2023-01-09 17:48 UTC, Hookwitz requested changes

2023-01-09 17:48 UTC, Hookwitz commented on .github/workflows/auto-approve-and-merge.yml
> +      pull-requests: write
I believe the addition of `contents: write` is required for permissions. I have been attempting to enable a similar workflow in the jsonix repo and had to add this permission to actually merge.

2023-01-10 16:48 UTC, wdower commented on setup-dev-env.sh
> +if [ -f .env ]; then
Good catch.

2023-01-13 15:02 UTC, em-c-rod approved these changes

2023-01-13 15:29 UTC, Hookwitz approved these changes

2023-01-17 20:26 UTC, merged