Disallowed saving duplicate group names in the frontend
mitre/heimdall2 pull request #4722
Opened 2023-07-17 19:56 UTC by Rlin232

2023-07-25 22:51 UTC, Amndeep7 requested changes

2023-07-25 22:51 UTC, Amndeep7 commented on apps/frontend/src/components/global/groups/GroupModal.vue
> +    this.uniqueName = !GroupsModule.allGroups.some(
why are we doing the double negation?  feels like the variable name should just be changed

2023-07-25 22:51 UTC, Amndeep7 commented on apps/frontend/src/components/global/groups/GroupModal.vue
> +    if (!this.uniqueName) SnackbarModule.failure(`Group names must be unique`);
one line if statements are bad, always use curly braces

2023-07-25 22:51 UTC, Amndeep7 commented on test/integration/groups.cy.ts
we should be testing the duplicate names restriction too

2023-07-25 22:51 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
> +    await queryInterface.sequelize.query(`CALL update_group_names_transaction()`)
why are we writing the transaction and then calling it as opposed to using sequelize.transaction?

2023-07-25 22:51 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
> +      offSet_cnt INTEGER :=1;
seems like spaces are fine here (and elsewhere) for assignment

```suggestion
      offSet_cnt INTEGER := 1;
```

2023-07-25 22:51 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
> +      check_name boolean := true;
use consistent naming patterns.  i'm not sure what it is for sql, but a mix of stringcase and camelcase at teh same time probably isn't it.

also use consistent capitalization - why is boolean all lower case whereas all the others are all caps

2023-07-25 22:51 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
> +      -- exit when no more records are available in the resul set
```suggestion
      -- exit when no more records are available in the result set
```

2023-07-25 22:51 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
does this handle that usecase that we discussed where

```
a
a
a-2
```

turns into 

```
a
a-2
a-2
```

(and therefore still has a dupe)

2023-07-27 15:27 UTC, Rlin232 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
For an 
`a, a, a-2`
It will turn into `a-1, a-3, a-2` respectively.

2023-07-27 15:58 UTC, Rlin232 commented on apps/backend/src/groups/groups.service.ts
Made the return type void (as it's a function that does a modification)

2023-07-27 16:00 UTC, Rlin232 commented on apps/backend/src/groups/groups.service.ts
>      groupToUpdate.update(groupDto);
Opted for the latter option, for the sake of consistency with updategroupuserrole

2023-07-31 16:48 UTC, Amndeep7 commented on apps/backend/migrations/20230725092535-change-group-names-to-unique.js
> +    await queryInterface.sequelize.query(`CALL update_group_names_transaction()`)
why would it be necessary to fix them again?  this is just to transition the group names the one time.  after that, our systems should be able to enforce the uniqueness requirement.  if the user goes in and manually mucks around with the group names within the db itself, that's on them to fix.

2023-08-01 23:32 UTC, Amndeep7 approved these changes

2023-08-01 23:49 UTC, merged