Possible Copy Workaround For HTTP
mitre/heimdall2 pull request #5235
Opened 2023-11-11 04:08 UTC by ChrisHinchey

**Needs Testing!**
- [ ] Fixes #5038

2023-11-14 05:07 UTC, Amndeep7 approved these changes

2023-11-14 05:10 UTC, Amndeep7 commented
@ChrisHinchey I've approved this cause I believe it should work.  Can you properly test it tho to confirm?  Pretty sure the easiest way to do so would be to spin up a heimdall demo locally (with no changes) or a docker instance with the nginx config / docker compose potentially needing adjustment to expose :80

2023-11-14 05:12 UTC, Amndeep7 commented
do the research but i'm pretty sure the sonarqube warning can be ignored cause there's no actual replacement for that deprecation

2023-11-14 07:51 UTC, ChrisHinchey commented
> do the research but i'm pretty sure the sonarqube warning can be ignored cause there's no actual replacement for that deprecation

Yeah, it seems like the new API just isn't fully implemented so there isn't a way around it at the moment

2023-11-14 08:06 UTC, ChrisHinchey commented
> @ChrisHinchey I've approved this cause I believe it should work. Can you properly test it tho to confirm? Pretty sure the easiest way to do so would be to spin up a heimdall demo locally (with no changes) or a docker instance with the nginx config / docker compose potentially needing adjustment to expose :80

I did spin up a heimdall instance locally, so it should be using the unsecured copy, but it seems like it is still using the secure copy.  Not sure if it is a browser thing (tried Firefox and Chrome), but I can't seem to make it use the unsecured version, which is the reason for the note at the top of the PR

2023-11-14 20:15 UTC, Amndeep7 commented
This functionality is still wrong:

heimdall: clipboard is there but empty 
<img width="241" alt="image" src="https://github.com/mitre/heimdall2/assets/2015821/9d569ddb-7100-43b0-af98-1e7f9047bfd1">

neverssl: clipboard is not there 
<img width="176" alt="image" src="https://github.com/mitre/heimdall2/assets/2015821/9ae20954-54f4-4a62-b1bd-9306b7696aee">

github: clipboard is there and object is populated with functions 
<img width="390" alt="image" src="https://github.com/mitre/heimdall2/assets/2015821/7ac77da6-9cc1-4989-b336-07c4fd57a6bb">

the if statement should probably check both if the clipboard object exists and also if the function we need exists within it

2023-12-05 02:58 UTC, Amndeep7 requested changes
@ChrisHinchey please see the above comment

2023-12-05 23:57 UTC, Amndeep7 commented on apps/frontend/src/components/generic/CopyButton.vue
> +    document.execCommand('copy');
need to capture the return value from here and manually throw an error if it's false

"A boolean value that is false if the command is unsupported or disabled."

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

2023-12-06 00:09 UTC, Amndeep7 approved these changes

2023-12-06 02:33 UTC, merged