Upgrade to aws sdk v3
mitre/heimdall2 pull request #5310
Opened 2023-12-04 18:58 UTC by Amndeep7

2023-12-04 23:25 UTC, ChrisHinchey approved these changes
After demo and reviewing code it looks good to me

2023-12-05 13:08 UTC, aaronlippold requested changes
Other than making sure we have the right environment variable or flag interface for the AWS credentials should they need to override them and allowing for the insecure flag or environment variable for verify SSL Certs it looks pretty straightforward.

2023-12-05 18:19 UTC, Amndeep7 commented on apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
> +      this.region || 'us-east-1',
It is documented to the degree that the input box on the modal says that the default is us-east-1

2023-12-05 18:21 UTC, Amndeep7 commented on apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
> +      this.region || 'us-east-1',
![Uploading image.png…]()

2023-12-05 18:22 UTC, Amndeep7 commented on apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
> +      this.region || 'us-east-1',
![image](https://github.com/mitre/heimdall2/assets/2015821/87144d1b-43cc-4b42-9cfd-2343c9a2b460)

2023-12-05 18:24 UTC, Amndeep7 commented on apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
> +      this.region || 'us-east-1',
The other values must be supplied by the user every time.

2023-12-05 18:31 UTC, Amndeep7 commented on libs/hdf-converters/src/aws-config-mapper.ts
> +    verifySSLCertificates = true,
The true is just the default value.  The mapper already supports insecure.  We just don't support custom CAs here.

https://github.com/mitre/heimdall2/blob/master/libs/hdf-converters/src/aws-config-mapper.ts#L28
https://github.com/mitre/saf/blob/main/src/commands/convert/aws_config2hdf.ts#L20

2023-12-05 18:33 UTC, Amndeep7 commented on libs/hdf-converters/src/aws-config-mapper.ts
> +    verifySSLCertificates = true,
Actually I lied, forgot that I added in the ability to do the CA already.  Look at the line below.

2023-12-05 18:33 UTC, aaronlippold approved these changes

2023-12-06 19:32 UTC, merged