Add tag in results view fix
mitre/heimdall2 pull request #5432
Opened 2024-01-12 03:08 UTC by georgedias

Fixes issue #5425

2024-01-12 22:16 UTC, em-c-rod approved these changes

2024-01-13 21:17 UTC, Amndeep7 approved these changes

2024-01-13 21:17 UTC, Amndeep7 commented on apps/frontend/src/store/data_filters.ts
> +    return this.selectedProfileIds.length > 0 ? true : false;
```suggestion
    return this.selectedProfileIds.length > 0;
```

2024-01-13 21:20 UTC, Amndeep7 commented
Would appreciate that one codesmell fix but not gonna make myself a blocker for it.  Feel free to merge whenever @georgedias

2024-01-13 21:27 UTC, Amndeep7 requested changes

2024-01-13 21:27 UTC, Amndeep7 commented on apps/frontend/src/components/global/tags/TagRow.vue
Actually looks like there's still an issue.

Replication:
1. Save a file to the db
2. Give it a tag from the results view
3. Give it a tag from the db view
4. Give a new tag from the results view - see that the tag you gave in the db view disappeared from the 'already applied' list and when you save this new tag list it'll disappear from the card as well


6. Save the tag list from there - watch your db tag go away unless you refreshed between steps 3 and 4

2024-01-13 21:31 UTC, Amndeep7 commented
https://github.com/mitre/heimdall2/assets/2015821/d5d4504f-9ee0-4541-88ce-df35efcd9c4d

2024-01-13 21:34 UTC, Amndeep7 commented
I made a heroku deployment to do the testing but it'll probably expire when you look at this again on tuesday

2024-01-18 19:17 UTC, wdower approved these changes

2024-01-18 19:39 UTC, Amndeep7 approved these changes

2024-01-18 19:57 UTC, wdower commented
Tested on Heroku; the tagging buttons for both results view and the loading modal are synced appropriately

2024-01-18 19:57 UTC, merged