Add Users to Evaluations, Cleanup ABAC, Convert all PrimaryKeys to strings
mitre/heimdall2 pull request #587
Opened 2020-12-03 17:57 UTC by rbclark

This PR is necessary in order to make #334 and fixes #21 (I think, @Bialogs please verify there is nothing left in #21 that I missed).

As part of this PR, all of the Policies are removed from the database and are instead stored in a file as part of the application. This fixes type mismatches between the return values from the database and the application itself. The database for heimdall server uses BigInt for all of it's primary keys. A BigInt can be larger than a javascript number. Due to this, the type that comes from postgres for BigInt fields is string, not number. All of the types in the application stating that it is a number are incorrect, and are fixed in this PR.

2020-12-16 19:24 UTC, Bialogs requested changes

2020-12-16 19:24 UTC, Bialogs commented on apps/backend/test/evaluations.e2e-spec.ts
> +      it.only('should create an evaluation', async () => {
Left an only in here.

2020-12-16 19:24 UTC, Bialogs commented on apps/backend/test/users.e2e-spec.ts
> +        ).expect(HttpStatus.OK);
Why return OK when the test description/title is written like its expecting a failure?

2020-12-16 19:31 UTC, rbclark commented on apps/backend/src/users/user.model.ts
> +    return 'User';
I originally hoped for that as well, however at runtime everything in Javascript is just an object.

<img width="1189" alt="Screen Shot 2020-12-16 at 2 31 08 PM" src="https://user-images.githubusercontent.com/2308869/102397044-5c929580-3fab-11eb-8212-9b5453e97382.png">

https://casl.js.org/v4/en/guide/subject-type-detection#how-does-casl-detect-subject-type

2020-12-21 21:10 UTC, Bialogs approved these changes

2020-12-21 21:10 UTC, merged